apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dpl-nginx
  template:
    metadata:
      labels:
        app: pd-nginx
    containers:
    - name: nginx
        image: nginx:1.17-alpine
        ports:
        - containerPort: 80